public enum CommandType {
    FILE_REQUEST,
    FILE_MESSAGE,
    LIST_RESPONSE,
    LIST_MESSAGE,
    DELETE_REQUEST,
    RENAME_REQUEST,
    SIMPLE_MESSAGE,
    PATH_IN_REQUEST,
    PATH_RESPONSE,
    PATCH_UP,
    AUTH_REQUEST,
    AUTH_RESPONSE,
    REG_REQUEST,
    MK_DIR_REQUEST
}
